import { join } from "node:path"
import {
  type IssueContext,
  fileExists,
  getConfig,
  ghRaw,
  git,
  log,
  logStep,
  readFile,
} from "../utils.js"

/**
 * Create the pull request. Pushes the branch and creates a PR via gh CLI.
 */
export async function stepCreatePR(ctx: IssueContext): Promise<boolean> {
  const cfg = getConfig()

  // Check if PR already exists
  if (await hasOpenPR(ctx.branch)) {
    logStep("Create PR", ctx, true)
    return true
  }

  logStep("Create PR", ctx)

  // Push branch to remote
  await git(["push", "-u", cfg.remote, ctx.branch])

  // Build PR body
  const reviewPath = join(ctx.issueDir, "review.md")
  const reviewSummary = fileExists(reviewPath)
    ? readFile(reviewPath).slice(0, 2000)
    : "No review summary available."

  const closesRef = ctx.repo === cfg.monorepo
    ? `Closes #${ctx.number}`
    : `Closes ${ctx.repo}#${ctx.number}`

  const body = [
    `## Summary`,
    ``,
    `Automated implementation for: **${ctx.title}**`,
    ``,
    closesRef,
    ``,
    `## Pipeline Artifacts`,
    ``,
    `- Research: \`.auto-pr/${ctx.repoShort}/issue-${ctx.number}/research.md\``,
    `- Plan: \`.auto-pr/${ctx.repoShort}/issue-${ctx.number}/plan.md\``,
    `- Implementation Plan: \`.auto-pr/${ctx.repoShort}/issue-${ctx.number}/plan-implementation.md\``,
    `- Review: \`.auto-pr/${ctx.repoShort}/issue-${ctx.number}/review.md\``,
    ``,
    `## Review Summary`,
    ``,
    reviewSummary,
    ``,
    `---`,
    `Generated by auto-pr pipeline`,
  ].join("\n")

  // Create PR
  const prUrl = await ghRaw([
    "pr", "create",
    "--repo", cfg.monorepo,
    "--head", ctx.branch,
    "--title", ctx.title,
    "--body", body,
    "--label", cfg.triggerLabel,
  ])

  if (prUrl) {
    log(`PR created: ${prUrl}`)
  } else {
    console.error("Failed to create PR")
    return false
  }

  return true
}

async function hasOpenPR(branch: string): Promise<boolean> {
  const out = await ghRaw([
    "pr", "list",
    "--repo", getConfig().monorepo,
    "--head", branch,
    "--state", "open",
    "--json", "number",
  ])
  try {
    const prs = JSON.parse(out)
    return Array.isArray(prs) && prs.length > 0
  } catch {
    return false
  }
}
